FROM anandmatt/spark_base

# Set default environment variables. These can also be set at the command line when invoking /bin/spark-submit
ENV MASTER_CONTAINER_NAME=spark-master
# ENV SPARK_EXECUTOR_MEMORY=6G
# ENV SPARK_EXECUTOR_CORES=3

# Install libraries
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y openjdk-17-jdk
RUN apt install -y python3-pip
COPY ./requirements.txt .
RUN python3 -m pip install -r requirements.txt
RUN python3 -m pip install jupyterlab --user

EXPOSE 4040 8888