FROM anandmatt/spark_base

ENV SPARK_MASTER_PORT 7077
ENV SPARK_MASTER_WEBUI_PORT 8080
ENV SPARK_MASTER_LOG /usr/local/spark/logs

# Install libraries
RUN apt-get update
RUN apt-get -y upgrade
RUN apt install -y python3-pip
COPY ./requirements.txt .
RUN python3 -m pip install -r requirements.txt

EXPOSE 7077 8080

# ENTRYPOINT $SPARK_HOME/bin/spark-class org.apache.spark.deploy.master.Master
CMD $SPARK_HOME/sbin/start-master.sh